title: >-
  #besserentscheiden . Ihre Pnyx, Ihre Dialogplattform zur St√§rkung der
  Demokratie
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.4946237
  brandStrength: 0.5017921
  lightness: 0.7885305
  brandColors:
    - '#D4E9EA'
    - '#23060A'
    - '#742427'
    - '#D0736F'
    - '#EFC0BC'
  rhythmicContrast: 0.6827957
cta:
  version: null
  bucket: null
  domain: null
analytics:
  twitter: null
  facebook: null
  google: null
favicon: null
name: '#besserentscheiden'
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.3620072
layout_spectrum: 0.570802
